version: "3.7"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/var/www/api1
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
    links:
      - php
    depends_on:
      - php
      - postgres
    volumes:
      - ./backend:/var/www/api1
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: backend
      dockerfile: docker/Dockerfile
    container_name: php_fpm
    volumes:
      - ./backend:/var/www/api1
    ports:
      - "9000:9000"
    links:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - 5432:5432
